### PR TITLE
Fixes #1599 - Wrong processing of Set-Cookie with "expires" with Jetty client.

### LINKED ISSUE #1599: Wrong processing of Set-Cookie with "expires" with Jetty client
**CometD version(s)**

8.0-beta1

**Java version & vendor** (use: `java -version`)

openjdk version "17.0.9" 2023-10-17
OpenJDK Runtime Environment (build 17.0.9+9-Ubuntu-122.04)
OpenJDK 64-Bit Server VM (build 17.0.9+9-Ubuntu-122.04, mixed mode, sharing)

**Description**

When Set-Cookie header contains "expires", like `BrowserId=be7II763489fhwcun5pA; domain=.salesforce.com; path=/; expires=Thu, 02-Jan-2025 14:21:47 GMT; Max-Age=31536000`, cometd fails to process it and does not send it in following requests. The reason is commit 62c4663ead0d9865240ca213b79c13be02cad59f which changed `field.getValue()` into `field.getValueList()`. The problem is that Jetty `HttpField.getValueList()` treats the header value as CSV and splits it by comma. So the result is list with two values: `BrowserId=be7II763489fhwcun5pA; domain=.salesforce.com; path=/; expires=Thu` and `02-Jan-2025 14:21:47 GMT; Max-Age=31536000`. Frankly, I don't know how multiple cookies can be set by single Set-Cookie header as RFC 6265 does not seem to allow that so I don't see a reason for using `getValueList()` instead of `getValue()`.

**How to reproduce?**

Not sure, I'm using cometd to connect to Salesforce to read notifications.

### PR DESCRIPTION
**Pull request by sbordet**
Fixed handling of the header value in case it is `Set-Cookie`. 
Removed support for `Set-Cookie2`.

### CODE REVIEW

File: cometd-java/cometd-java-client/cometd-java-client-http/cometd-java-client-http-jetty/src/main/java/org/cometd/client/http/jetty/JettyHttpClientTransport.java [hunk 1]
```diff
@@ -230,12 +229,12 @@ private ResponseListener(TransportListener listener, List<Message.Mutable> messa
...
             if (response.getStatus() == HttpStatus.OK_200) {
-                HttpHeader header = field.getHeader();
-                if (header == HttpHeader.SET_COOKIE || header == HttpHeader.SET_COOKIE2) {
+                String name = field.getName();
+                if (HttpHeader.SET_COOKIE.is(name)) {
                     // We do not allow cookies to be handled by HttpClient, since one
                     // HttpClient instance is shared by multiple BayeuxClient instances.
                     // Instead, we store the cookies in the BayeuxClient instance.
-                    Map<String, List<String>> cookies = Map.of(field.getName(), field.getValueList());
+                    Map<String, List<String>> cookies = Map.of(field.getName(), List.of(field.getValue()));
```
Comment (lorban) [inline cometd-java/cometd-java-client/cometd-java-client-http/cometd-java-client-http-jetty/src/main/java/org/cometd/client/http/jetty/JettyHttpClientTransport.java]: Either reuse the `name` variable here, or inline it.

**Review by lorban — APPROVED** [review]
Just one nit, otherwise LGTM.
